export const SEARCH_MOVIES_FOR_NOMINATION = "SEARCH_MOVIES_FOR_NOMINATION";
export const DELETE_MOVIES_FROM_NOMINATION = "DELETE_MOVIES_FROM_NOMINATION";

export const ADD_MOVIES_FOR_NOMINATION = "ADD_MOVIES_FOR_NOMINATION";